- BUG_REPORTS/messages/0
Trivial change to trigger webhook update
> Update bug_reports webhook

- .github/scripts/webhooks.sh
Will attempt to send messages not currently in `$HOOK/ids`, and save the returned message ids.
> Account for appending new messages to webhook

- .github/scripts/webhooks.sh
- .github/workflows/test.yml
- .github/workflows/webhooks.yml
Adds test to make sure all webhook env vars are mapped when calling webhooks.sh.
Also sets `allowed_mentions: {parse: []}}` when sending messages to disable all pings.
> [no ci] Update test script

- RULES/messages/0
Slurs should not be used even when not used against the affected group, and will be moderated even when used towards oneself.
> Clarify Rule 1 regarding using slurs

- RULES/messages/0
- RULES/messages/1
Rule 3: don't cause *or contribute to* drama, players->people.
Rule 12: spoilers must be tagged appropriately.
> Update rules 3 and 12, use markdown for TOS links

- .github/scripts/webhooks.sh
- .github/workflows/webhooks.yml
- .gitignore
Also adds a special case to account for running from Windows using curl without Unicode support.
> Implement test workflow, account for all changes in merge

- CELESTE/messages/0
Added Isabelle to the ping list for Hardest Maps Clear List
> Update Hard Maps Clear List message in celeste pin

- CELESTE/messages/0
Added Parrot Dash to the ping list for Hardest Maps Clear List
> Update Hard Maps Clear List message in celeste pin (again)

- MODDING_WELCOME/messages/0
Updated the modding help channel ID
> Update modding welcome webhook

- DEATHLESS_STRATS/messages/0
added welcome and "- Make sure that if you're using abbreviations they're easily understandable."
> Update deathless_strats webhook message

- .github/scripts/test.sh
- .github/scripts/webhooks.sh
- .github/workflows/webhooks.yml
- .hooks/pre-commit
- .testing/runtests.sh
- ASSET_MAKING/messages/0
- RULES/messages/0
- RULES/messages/1
- RULES/messages/2
Updates Rules and Asset Making webhooks to comply with new pre-commit requirements.
> Add manual testing script and pre-commit hook

- SPEEDRUN_HELP/messages/0
> added AverageImposter video to sr_help pin 1

- SPEEDRUN_HELP/messages/1
> edited link for cpop tutorial

- SPEEDRUN_HELP/messages/0
- SPEEDRUN_HELP/messages/1
> removed a few less used resources/added a few more

- RULES/messages/1
> dev chat link, 36000 members thing

- SPEEDRUN_HELP/messages/1
- SPEEDRUN_WELCOME/messages/0
> updated and condensed #speedrun_welcome and #srhelp with new resources

- ROLES/messages/0
> #roles moderator descriptions if we're going to do that

- ROLES/messages/0
> Replace duplicate gen mod mention with meta mod

- CELESTE/messages/0
- DEATHLESS_GENERAL/messages/0
> removing kriog from pinned messages on golden lists

- SPEEDRUN_WELCOME/messages/0
> added dan to sr_welcome

- MAP_MAKING/messages/0
- MODDING_GENERAL/messages/0
- MODDING_WELCOME/messages/0
> Replace references to Ahorn with Loenn, update links

- RULES/messages/0
- RULES/messages/1
> updated rules 2 and 7 to the recent proposals

- SPEEDRUN_HELP/messages/0
- SPEEDRUN_HELP/messages/1
> Updated both resource #speedrun_help pins for better management of resources 

- RULES/messages/2
> Added an explanation of the media role to the rules

- SPEEDRUN_HELP/messages/1
Added Farewell Cue Collection and removed the second mention of the cpop tutorial
> Update #speedrun-help pins

- CELESTE/messages/0
Waiting on confirmation that this is something I should do
> 'or' -> 'and'

- CELESTE/messages/0
- RULES/messages/1
- RULES/messages/2
Those changes were made to update #rules and #celeste pins in a fork, as we did not have access to the original repository at the time. This PR merges the changes back to the "real" repository, to be able to get rid of the fork now that the access rights situation has been solved.
> Merge #rules and #celeste changes back into upstream

- RULES/messages/1
> Remove #dev_greetings_appreciation from rule 13

- MAP_MAKING/messages/0
old link both deadnamed and is no longer functional, so update to respect and actually work
> update custom entity list link

- MODDING_WELCOME/messages/0
new channel modding updates to be added to modding welcome ping in line about modding showcase and modding wip, channels that serve a very similar purpose
> add modding updates to modding welcome pin
